### ISSUE TITLE
isPhone mongoose validation error

### ISSUE THREAD

**Issue by eliataylor** [eliataylor/ampp-keystone#14]
```2017-09-23T19:04:48.543675+00:00 app[web.1]: GET /keystone/api/users?fields=name%2Cemail%2Cmedium%2CisAdmin&limit=100&sort=name&expandRelationshipFields=true 304 38.961 ms
2017-09-23T19:05:28.457438+00:00 app[web.1]: TypeError: This library (validator.js) validates strings only
2017-09-23T19:05:28.457449+00:00 app[web.1]:     at assertString (/app/node_modules/validator/lib/util/assertString.js:11:11)
2017-09-23T19:05:28.457455+00:00 app[web.1]:     at model.isMobilePhone (/app/node_modules/validator/lib/isMobilePhone.js:71:30)
2017-09-23T19:05:28.457457+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/schematype.js:742:28
2017-09-23T19:05:28.457458+00:00 app[web.1]:     at Array.forEach (native)
2017-09-23T19:05:28.457459+00:00 app[web.1]:     at SchemaString.SchemaType.doValidate (/app/node_modules/mongoose/lib/schematype.js:710:19)
2017-09-23T19:05:28.457456+00:00 app[web.1]:     at model.validator (/app/node_modules/mongoose-validator/lib/mongoose-validator.js:72:15)
2017-09-23T19:05:28.457459+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/document.js:1375:9
2017-09-23T19:05:28.457460+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2017-09-23T19:05:28.457461+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:98:9)
2017-09-23T19:05:28.531073+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/keystone/api/users/create" host=afternoon-mesa-52732.herokuapp.com request_id=e6401d04-7e6c-4d24-82e7-091b7c04d041 fwd="50.99.73.7" dyno=web.1 connect=0ms service=152ms status=503 bytes=0 protocol=http
2017-09-23T19:05:28.602379+00:00 heroku[web.1]: State changed from up to crashed
2017-09-23T19:05:28.604560+00:00 heroku[web.1]: State changed from crashed to starting
2017-09-23T19:05:28.588069+00:00 heroku[web.1]: Process exited with status 1
2017-09-23T19:05:34.704278+00:00 heroku[web.1]: Starting process with command `NODE_ENV=production node keystone.js`
```

**Comment by r3wt** [comment]
pushed a potential fix for this as well.

**Comment by eliataylor** [comment]
fixed. also added two more validators and basic `req.flash("error", msg)` calls to display validations errors
